import { ProductDetail } from './product-detail';
import { Item } from './gallery';

export const ProductList: Array<Product> = [
  {
    id: 1,
    code: 'sp1-0002',
    name:'Sản phẩm 1',
    category: 1,
    price: 150000,
    currencyUnit: 'VND',
    unit: 'kg',
    thumbnail: '../../assets/products/others/oc-chuoi-dau-thumbnail.jpg',
    imgBanner: '../../assets/imgs/banners/banner-1.png',
    sortDescription: 'Đây là sản phẩm 1',
    highlight: true,
    productDetail: null,
    albumImg: [],
    albumVideo: []
  },
  { 
    id: 2,
    code: 'sp2-0005',
    name:'Sản phẩm 2',
    category: 1,
    price: 120000,
    currencyUnit: 'VND',
    unit: 'kg',
    thumbnail: '../../assets/products/others/oc-chuoi-dau-thumbnail.jpg',
    imgBanner: '../../assets/imgs/banners/banner-2.png',
    sortDescription: 'Đây là sản phẩm 2',
    highlight: true,
    productDetail: null,
    albumImg: [],
    albumVideo: []
  },
  {
    id: 3,
    code: 'sp3-0005',
    name:'Sản phẩm 3',
    category: 1,
    price: 250000,
    currencyUnit: 'VND',
    unit: 'kg',
    thumbnail: '../../assets/products/others/oc-chuoi-dau-thumbnail.jpg',
    imgBanner: '',
    sortDescription: 'Đây là sản phẩm 3',
    highlight: false,
    productDetail: null,
    albumImg: [],
    albumVideo: []
  },
  {
    id: 4,
    code: 'sp4-0005',
    name:'Sản phẩm 4',
    category: 1,
    price: 220000,
    currencyUnit: 'VND',
    unit: 'kg',
    thumbnail: '../../assets/products/others/oc-chuoi-dau-thumbnail.jpg',
    imgBanner: '../../assets/imgs/banners/banner-4.png',
    sortDescription: 'Đây là sản phẩm 4',
    highlight: true,
    productDetail: null,
    albumImg: [],
    albumVideo: []
  },
  {
    id: 5,
    code: 'sp5-0005',
    name:'Sản phẩm 5',
    category: 2,
    price: 190000,
    currencyUnit: 'VND',
    unit: 'kg',
    thumbnail: '../../assets/products/others/oc-chuoi-dau-thumbnail.jpg',
    imgBanner: '../../assets/imgs/banners/banner-3.png',
    sortDescription: 'Đây là sản phẩm 5',
    highlight: false,
    productDetail: null,
    albumImg: [],
    albumVideo: []
  },
  {
    id: 6,
    code: 'sp6-00021',
    name:'Sản phẩm 6',
    category: 2,
    price: 220000,
    currencyUnit: 'VND',
    unit: 'kg',
    thumbnail: '../../assets/products/others/oc-chuoi-dau-thumbnail.jpg',
    imgBanner: '../../assets/imgs/banners/banner-3.png',
    sortDescription: 'Đây là sản phẩm 6',
    highlight: false,
    productDetail: null,
    albumImg: [],
    albumVideo: []
  }
];


export interface Product{
  id: number,
  code: string,
  name: string,
  category: number,
  price: number,
  currencyUnit: string,
  unit: string,
  thumbnail: string,
  imgBanner: string,
  sortDescription: string,
  highlight: boolean,
  quantity?: number,
  productDetail: ProductDetail | null,
  albumImg: Array<Item> | [],
  albumVideo: Array<Item> | []
}